#! /bin/bash
if [ -z "$1" ]; then
printf "Geef be string mee eh vriendmakker!"
else
echo "\$TTL	300
@	IN	SOA	ns.reda-boussabat.sb.uclllabs.be $1.reda-boussabat.sb.uclllabs.be.(
		 2020110801	; Serial
			300	; Refresh
			300	; Retry
			300	; Expire
			300)	; Negative Cashe TTL
; A records for name servers
@	IN	NS	ns.reda-boussabat.sb.uclllabs.be.
ns	IN	A	193.191.177.198
@	IN	A	193.191.177.198" > /etc/bind/zones/$1.reda-boussabat.sb.uclllabs.be
echo -e "
zone \"$1.reda-boussabat.sb.uclllabs.be\"{
	type master;
	file \"/etc/bind/zones/$1.reda-boussabat.sb.uclllabs.be\";
	notify yes;
};" >> /etc/bind/named.conf.local

echo -e "$1	IN	NS	ns.reda-boussabat.sb.uclllabs.be." >> /etc/bind/zones/db.reda-boussabat.sb.uclllabs.be
SERIAL_NUM=$(grep -Po '\d+(?=\s+; Serial)' /etc/bind/zones/db.reda-boussabat.sb.uclllabs.be) 
SERIAL_LIN=$(grep -Po '\s+; Serial' /etc/bind/zones/db.reda-boussabat.sb.uclllabs.be)
SERIAL_ALL=$(grep -Po '\d+\s+; Serial' /etc/bind/zones/db.reda-boussabat.sb.uclllabs.be)  
NEW_NUM=$(("$SERIAL_NUM" + 1)) 
sed -i "s/$SERIAL_ALL/$NEW_NUM$SERIAL_LIN/g" /etc/bind/zones/db.reda-boussabat.sb.uclllabs.be

systemctl restart bind9
fi
