#! /bin/bash


ZONE=$(grep -Po '.{1,}(?=.reda-boussabat.sb.uclllabs.be)' <<< "$1")


if [ -z "$ZONE" ]; then
	printf "First make a domain then run this script using that domain"
else
	touch /etc/apache2/sites-available/$ZONE.conf
	echo -e "<VirtualHost *:80>
		ServerAdmin webmaster@localhost
		ServerName $1
		DocumentRoot /var/www/html/$ZONE
		ErrorLog \${APACHE_LOG_DIR}/$ZONE.log 
		CustomLog \${APACHE_LOG_DIR}/$ZONE.log  combined
	</VirtualHost>" >> /etc/apache2/sites-available/$ZONE.conf

	mkdir /var/www/html/$ZONE
	touch /var/www/html/$ZONE/index.html

	echo "<html> <p>welcome $ZONE</p> </html>" >> /var/www/html/$ZONE/index.html

	a2ensite $ZONE.conf

	echo "$ZONE	IN	A	193.191.177.198" >> /etc/bind/zones/db.reda-boussabat.sb.uclllabs.be

	SERIAL_NUM=$(grep -Po '\d+(?=\s+; Serial)' /etc/bind/zones/db.reda-boussabat.sb.uclllabs.be)
	SERIAL_LIN=$(grep -Po '\s+; Serial' /etc/bind/zones/db.reda-boussabat.sb.uclllabs.be)
	SERIAL_ALL=$(grep -Po '\d+\s+; Serial' /etc/bind/zones/db.reda-boussabat.sb.uclllabs.be)
	NEW_NUM=$(("$SERIAL_NUM" + 1))
	sed -i "s/$SERIAL_ALL/$NEW_NUM$SERIAL_LIN/g" /etc/bind/zones/db.reda-boussabat.sb.uclllabs.be

	systemctl restart bind9
	systemctl restart apache2
fi
